name: Generate Snake

on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies
        run: npm install



      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oluwafemidan/oluwafemidan.git
          git add .
          git commit -m "Update snake animations"
          git push -f
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
